#!/usr/bin/env node
/**
 * sync-tools — pull REAL subagents and slash commands from a hot, MIT-licensed
 * community repo (wshobson/agents, 36k+ stars) instead of hand-authoring them.
 *
 * Each file is fetched, **validated by agentlint**, and only kept if it passes
 * with zero errors. The result is written to `apps/web/src/lib/tools-catalog.ts`
 * (consumed by `gen-catalog.mjs`) plus a `docs/TOOL-SOURCES.md` status report.
 *
 * Run: `npm run sync:tools` (build core first).
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { lintFiles, parseFrontmatter } from '../packages/core/dist/index.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(here, '..');
const OUT_TS = path.join(ROOT, 'apps', 'web', 'src', 'lib', 'tools-catalog.ts');
const OUT_DOC = path.join(ROOT, 'docs', 'TOOL-SOURCES.md');

const OWNER = 'wshobson';
const REPO = 'agents';
const REF = 'main';
// Keep the sync bounded (and the catalog curated): cap how many of each we take.
const MAX_AGENTS = 70;
const MAX_COMMANDS = 40;
const MAX_SKILLS = 70;

const raw = (p) => `https://raw.githubusercontent.com/${OWNER}/${REPO}/${REF}/${p}`;

async function getJson(url) {
  const res = await fetch(url, { headers: { 'user-agent': 'agentlint-sync-tools' } });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return res.json();
}
async function getText(url) {
  const res = await fetch(url, { headers: { 'user-agent': 'agentlint-sync-tools' } });
  if (!res.ok) return null;
  return res.text();
}

/** Slugify a plugin folder into a tag. */
const tagFor = (p) => {
  const m = p.match(/^plugins\/([^/]+)\//);
  return m ? m[1] : 'community';
};

function buildItem(kind, p, content) {
  const fm = parseFrontmatter(content);
  const name = fm.data && typeof fm.data['name'] === 'string' ? fm.data['name'] : '';
  if (!name) return null;

  let topKind, id, targetPath, tags;
  if (kind === 'skill') {
    topKind = 'skill';
    id = `skill-wshobson-${name}`;
    targetPath = `.claude/skills/${name}/SKILL.md`;
    tags = ['skill', tagFor(p)];
  } else if (kind === 'agent') {
    topKind = 'tool';
    id = `tool-agent-${name}`;
    targetPath = `.claude/agents/${name}.md`;
    tags = ['tool', 'subagent', tagFor(p)];
  } else {
    topKind = 'tool';
    id = `tool-command-${name}`;
    targetPath = `.claude/commands/${name}.md`;
    tags = ['tool', 'slash-command', tagFor(p)];
  }

  // Validate exactly as it will be used.
  const result = lintFiles([{ path: targetPath, content, kind }]);
  if (result.summary.errors > 0) return { rejected: true, name, errors: result.summary.errors };
  const desc = fm.data && typeof fm.data['description'] === 'string' ? fm.data['description'] : name;
  return {
    item: {
      id,
      kind: topKind,
      configKind: kind,
      name,
      title: name,
      description: desc.length > 200 ? desc.slice(0, 197) + '…' : desc,
      source: raw(p),
      license: 'MIT',
      tags,
      targetPath,
      content,
    },
  };
}

async function main() {
  const tree = await getJson(`https://api.github.com/repos/${OWNER}/${REPO}/git/trees/${REF}?recursive=1`);
  const paths = (tree.tree || []).map((t) => t.path);
  const agentPaths = paths.filter((p) => /^plugins\/[^/]+\/agents\/[^/]+\.md$/.test(p)).slice(0, MAX_AGENTS);
  const commandPaths = paths.filter((p) => /^plugins\/[^/]+\/commands\/[^/]+\.md$/.test(p)).slice(0, MAX_COMMANDS);
  const skillPaths = paths.filter((p) => /^plugins\/[^/]+\/skills\/[^/]+\/SKILL\.md$/.test(p)).slice(0, MAX_SKILLS);

  const items = [];
  const report = [];
  const seen = new Set();

  for (const [kind, list] of [['skill', skillPaths], ['agent', agentPaths], ['command', commandPaths]]) {
    for (const p of list) {
      const content = await getText(raw(p));
      if (content == null) {
        report.push({ p, status: 'fetch failed' });
        continue;
      }
      const built = buildItem(kind, p, content);
      if (!built) {
        report.push({ p, status: 'no name' });
      } else if (built.rejected) {
        report.push({ p, status: `rejected (${built.errors} errors)` });
      } else if (seen.has(built.item.id)) {
        report.push({ p, status: 'duplicate' });
      } else {
        seen.add(built.item.id);
        items.push(built.item);
        report.push({ p, status: 'synced', name: built.item.name });
      }
    }
  }

  items.sort((a, b) => a.id.localeCompare(b.id));

  const banner =
    '// AUTO-GENERATED by scripts/sync-tools.mjs — do not edit by hand.\n' +
    `// Real subagents & slash commands synced from github.com/${OWNER}/${REPO} (MIT),\n` +
    '// each validated by agentlint (0 errors). Refresh with `npm run sync:tools`.\n\n';
  writeFileSync(OUT_TS, banner + `export const TOOL_ITEMS = ${JSON.stringify(items, null, 2)};\n`);

  const synced = report.filter((r) => r.status === 'synced').length;
  const doc = [
    '# Synced tool sources',
    '',
    `Generated by \`scripts/sync-tools.mjs\` from [github.com/${OWNER}/${REPO}](https://github.com/${OWNER}/${REPO}) (MIT).`,
    'Each agent/command is fetched and **validated by agentlint**; only items with **0 errors** are kept.',
    '',
    `Synced **${synced}** of ${report.length} candidates.`,
    '',
    '> Tools retain their upstream MIT license. Not affiliated with the upstream authors.',
    '',
  ].join('\n');
  writeFileSync(OUT_DOC, doc);

  console.log(`tools: ${items.length} synced from ${OWNER}/${REPO} (of ${report.length} candidates).`);
}

main().catch((e) => {
  console.error('sync-tools failed:', e.message);
  // Do not crash the build chain: leave any existing tools-catalog.ts in place.
  process.exit(0);
});
