#!/usr/bin/env node
/**
 * sync-stars — refresh live star counts for the repo directory (Collections page).
 *
 * Reads `data/repo-directory.json` (the hand-curated list of Skills / MCP /
 * Tools repositories, grouped into collections), fetches the CURRENT star
 * count + description for every repo in batches via the GitHub GraphQL API,
 * writes the refreshed JSON back, and emits a generated TypeScript module the
 * web app renders (`apps/web/src/lib/repo-directory.generated.ts`).
 *
 * Network failures are non-fatal: a repo that can't be fetched keeps its
 * previously-synced numbers, so the build never breaks because GitHub was
 * unreachable.
 *
 * Auth: uses GITHUB_TOKEN (CI) or falls back to `gh auth token` (local).
 * Run: `npm run sync:stars`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(here, '..');
const DATA = path.join(ROOT, 'data', 'repo-directory.json');
const OUT_TS = path.join(ROOT, 'apps', 'web', 'src', 'lib', 'repo-directory.generated.ts');

function token() {
  if (process.env.GITHUB_TOKEN) return process.env.GITHUB_TOKEN;
  try {
    return execSync('gh auth token', { encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

async function fetchBatch(repos, auth) {
  // One aliased GraphQL query per batch — 1 request for up to 50 repos.
  const fields = repos
    .map((r, i) => {
      const [owner, name] = r.fullName.split('/');
      return `r${i}: repository(owner: ${JSON.stringify(owner)}, name: ${JSON.stringify(name)}) { stargazerCount description url isArchived }`;
    })
    .join('\n');
  const res = await fetch('https://api.github.com/graphql', {
    method: 'POST',
    headers: { Authorization: `bearer ${auth}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: `query {\n${fields}\n}` }),
  });
  if (!res.ok) throw new Error(`GraphQL HTTP ${res.status}`);
  const body = await res.json();
  return body.data ?? {};
}

const doc = JSON.parse(readFileSync(DATA, 'utf8'));
const auth = token();
let refreshed = 0;

if (!auth) {
  console.warn('sync-stars: no GitHub token — keeping previously-synced counts.');
} else {
  for (let i = 0; i < doc.repos.length; i += 50) {
    const batch = doc.repos.slice(i, i + 50);
    try {
      const data = await fetchBatch(batch, auth);
      batch.forEach((r, j) => {
        const node = data[`r${j}`];
        if (!node) return; // renamed/removed repo: keep old values
        r.stars = node.stargazerCount;
        if (node.description) r.description = node.description.trim();
        if (node.url) r.url = node.url;
        if (node.isArchived) r.archived = true;
        refreshed++;
      });
    } catch (err) {
      console.warn(`sync-stars: batch ${i / 50} failed (${err.message}) — keeping old values.`);
    }
  }
  doc.updated = new Date().toISOString();
}

doc.repos.sort((a, b) => b.stars - a.stars);
writeFileSync(DATA, JSON.stringify(doc, null, 2) + '\n');

const banner = `/**
 * GENERATED by scripts/sync-stars.mjs — do not edit by hand.
 * Curated directory of Skills / MCP / Tools repositories with synced star counts.
 * Source of truth: data/repo-directory.json. Refresh: \`npm run sync:stars\`.
 */
/* eslint-disable */
`;
writeFileSync(
  OUT_TS,
  banner +
    `export const REPO_DIRECTORY_UPDATED = ${JSON.stringify(doc.updated)};\n\n` +
    `export const REPO_DIRECTORY_ITEMS = ${JSON.stringify(doc.repos, null, 2)} as const;\n`,
);
console.log(`sync-stars: ${refreshed}/${doc.repos.length} repos refreshed; wrote ${path.relative(ROOT, OUT_TS)}`);
