// AUTO-GENERATED by scripts/sync-mcp.mjs — do not edit by hand.
// Popular MCP servers with their REAL published versions (npm/PyPI), each
// validated by agentlint (0 errors). Refresh with `npm run sync:mcp`.

export const MCP_ITEMS = [
  {
    "id": "mcp-brave-search",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "brave-search",
    "title": "Brave Search",
    "description": "Web and local search via the Brave Search API.",
    "source": "https://www.npmjs.com/package/@modelcontextprotocol/server-brave-search",
    "license": "MIT",
    "tags": [
      "mcp",
      "web",
      "search",
      "api"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"brave-search\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"@modelcontextprotocol/server-brave-search@0.6.2\"\n      ],\n      \"env\": {\n        \"BRAVE_API_KEY\": \"${BRAVE_API_KEY}\"\n      }\n    }\n  }\n}\n",
    "install": "claude mcp add brave-search -e BRAVE_API_KEY=${BRAVE_API_KEY} -- npx -y @modelcontextprotocol/server-brave-search@0.6.2",
    "envVars": [
      "BRAVE_API_KEY"
    ]
  },
  {
    "id": "mcp-context7",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "context7",
    "title": "Context7",
    "description": "Up-to-date, version-specific library docs and examples.",
    "source": "https://www.npmjs.com/package/@upstash/context7-mcp",
    "license": "MIT",
    "tags": [
      "mcp",
      "docs",
      "reference"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"context7\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"@upstash/context7-mcp@3.2.1\"\n      ]\n    }\n  }\n}\n",
    "install": "claude mcp add context7 -- npx -y @upstash/context7-mcp@3.2.1",
    "envVars": []
  },
  {
    "id": "mcp-everything",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "everything",
    "title": "Everything",
    "description": "The MCP reference/test server (tools, resources, prompts).",
    "source": "https://www.npmjs.com/package/@modelcontextprotocol/server-everything",
    "license": "MIT",
    "tags": [
      "mcp",
      "reference",
      "testing"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"everything\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"@modelcontextprotocol/server-everything@2026.1.26\"\n      ]\n    }\n  }\n}\n",
    "install": "claude mcp add everything -- npx -y @modelcontextprotocol/server-everything@2026.1.26",
    "envVars": []
  },
  {
    "id": "mcp-exa",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "exa",
    "title": "Exa Search",
    "description": "Neural web search and content retrieval via Exa.",
    "source": "https://www.npmjs.com/package/exa-mcp-server",
    "license": "MIT",
    "tags": [
      "mcp",
      "web",
      "search",
      "api"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"exa\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"exa-mcp-server@3.2.1\"\n      ],\n      \"env\": {\n        \"EXA_API_KEY\": \"${EXA_API_KEY}\"\n      }\n    }\n  }\n}\n",
    "install": "claude mcp add exa -e EXA_API_KEY=${EXA_API_KEY} -- npx -y exa-mcp-server@3.2.1",
    "envVars": [
      "EXA_API_KEY"
    ]
  },
  {
    "id": "mcp-fetch",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "fetch",
    "title": "Fetch",
    "description": "Fetch a URL and return its content as Markdown.",
    "source": "https://www.npmjs.com/package/mcp-server-fetch",
    "license": "MIT",
    "tags": [
      "mcp",
      "web",
      "http"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"fetch\": {\n      \"command\": \"uvx\",\n      \"args\": [\n        \"mcp-server-fetch==2026.6.4\"\n      ]\n    }\n  }\n}\n",
    "install": "claude mcp add fetch -- uvx mcp-server-fetch==2026.6.4",
    "envVars": []
  },
  {
    "id": "mcp-filesystem",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "filesystem",
    "title": "Filesystem",
    "description": "Read, write, and search files within allowed directories.",
    "source": "https://www.npmjs.com/package/@modelcontextprotocol/server-filesystem",
    "license": "MIT",
    "tags": [
      "mcp",
      "files",
      "local"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"filesystem\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"@modelcontextprotocol/server-filesystem@2026.1.14\",\n        \".\"\n      ]\n    }\n  }\n}\n",
    "install": "claude mcp add filesystem -- npx -y @modelcontextprotocol/server-filesystem@2026.1.14 .",
    "envVars": []
  },
  {
    "id": "mcp-firecrawl",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "firecrawl",
    "title": "Firecrawl",
    "description": "Crawl and scrape websites into clean Markdown.",
    "source": "https://www.npmjs.com/package/firecrawl-mcp",
    "license": "MIT",
    "tags": [
      "mcp",
      "web",
      "scraping",
      "api"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"firecrawl\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"firecrawl-mcp@3.21.0\"\n      ],\n      \"env\": {\n        \"FIRECRAWL_API_KEY\": \"${FIRECRAWL_API_KEY}\"\n      }\n    }\n  }\n}\n",
    "install": "claude mcp add firecrawl -e FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY} -- npx -y firecrawl-mcp@3.21.0",
    "envVars": [
      "FIRECRAWL_API_KEY"
    ]
  },
  {
    "id": "mcp-git",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "git",
    "title": "Git",
    "description": "Read, search, and manipulate a local Git repository.",
    "source": "https://www.npmjs.com/package/mcp-server-git",
    "license": "MIT",
    "tags": [
      "mcp",
      "git",
      "local"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"git\": {\n      \"command\": \"uvx\",\n      \"args\": [\n        \"mcp-server-git==2026.6.16\"\n      ]\n    }\n  }\n}\n",
    "install": "claude mcp add git -- uvx mcp-server-git==2026.6.16",
    "envVars": []
  },
  {
    "id": "mcp-github",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "github",
    "title": "GitHub",
    "description": "Manage issues, PRs, and repositories on GitHub.",
    "source": "https://www.npmjs.com/package/@modelcontextprotocol/server-github",
    "license": "MIT",
    "tags": [
      "mcp",
      "git",
      "github",
      "api"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"github\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"@modelcontextprotocol/server-github@2025.4.8\"\n      ],\n      \"env\": {\n        \"GITHUB_PERSONAL_ACCESS_TOKEN\": \"${GITHUB_PERSONAL_ACCESS_TOKEN}\"\n      }\n    }\n  }\n}\n",
    "install": "claude mcp add github -e GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN} -- npx -y @modelcontextprotocol/server-github@2025.4.8",
    "envVars": [
      "GITHUB_PERSONAL_ACCESS_TOKEN"
    ]
  },
  {
    "id": "mcp-linear",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "linear",
    "title": "Linear",
    "description": "Create and update issues and projects in Linear.",
    "source": "https://mcp.linear.app/sse",
    "license": "MIT",
    "tags": [
      "mcp",
      "issues",
      "api"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"linear\": {\n      \"type\": \"sse\",\n      \"url\": \"https://mcp.linear.app/sse\"\n    }\n  }\n}\n",
    "install": "claude mcp add --transport sse linear https://mcp.linear.app/sse",
    "envVars": []
  },
  {
    "id": "mcp-memory",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "memory",
    "title": "Memory",
    "description": "A persistent knowledge-graph memory across sessions.",
    "source": "https://www.npmjs.com/package/@modelcontextprotocol/server-memory",
    "license": "MIT",
    "tags": [
      "mcp",
      "memory",
      "state"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"memory\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"@modelcontextprotocol/server-memory@2026.1.26\"\n      ]\n    }\n  }\n}\n",
    "install": "claude mcp add memory -- npx -y @modelcontextprotocol/server-memory@2026.1.26",
    "envVars": []
  },
  {
    "id": "mcp-mongodb",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "mongodb",
    "title": "MongoDB",
    "description": "Query and inspect a MongoDB database.",
    "source": "https://www.npmjs.com/package/mongodb-mcp-server",
    "license": "MIT",
    "tags": [
      "mcp",
      "database"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"mongodb\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"mongodb-mcp-server@1.13.0\"\n      ],\n      \"env\": {\n        \"MDB_MCP_CONNECTION_STRING\": \"${MDB_MCP_CONNECTION_STRING}\"\n      }\n    }\n  }\n}\n",
    "install": "claude mcp add mongodb -e MDB_MCP_CONNECTION_STRING=${MDB_MCP_CONNECTION_STRING} -- npx -y mongodb-mcp-server@1.13.0",
    "envVars": [
      "MDB_MCP_CONNECTION_STRING"
    ]
  },
  {
    "id": "mcp-notion",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "notion",
    "title": "Notion",
    "description": "Read and update Notion pages and databases.",
    "source": "https://www.npmjs.com/package/@notionhq/notion-mcp-server",
    "license": "MIT",
    "tags": [
      "mcp",
      "docs",
      "api"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"notion\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"@notionhq/notion-mcp-server@2.4.0\"\n      ],\n      \"env\": {\n        \"NOTION_TOKEN\": \"${NOTION_TOKEN}\"\n      }\n    }\n  }\n}\n",
    "install": "claude mcp add notion -e NOTION_TOKEN=${NOTION_TOKEN} -- npx -y @notionhq/notion-mcp-server@2.4.0",
    "envVars": [
      "NOTION_TOKEN"
    ]
  },
  {
    "id": "mcp-playwright",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "playwright",
    "title": "Playwright",
    "description": "Drive a real browser for testing and scraping.",
    "source": "https://www.npmjs.com/package/@playwright/mcp",
    "license": "MIT",
    "tags": [
      "mcp",
      "browser",
      "testing",
      "web"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"playwright\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"@playwright/mcp@0.0.76\"\n      ]\n    }\n  }\n}\n",
    "install": "claude mcp add playwright -- npx -y @playwright/mcp@0.0.76",
    "envVars": []
  },
  {
    "id": "mcp-postgres",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "postgres",
    "title": "Postgres",
    "description": "Run read-only SQL queries and inspect a PostgreSQL schema.",
    "source": "https://www.npmjs.com/package/enhanced-postgres-mcp-server",
    "license": "MIT",
    "tags": [
      "mcp",
      "database",
      "sql"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"postgres\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"enhanced-postgres-mcp-server@1.0.1\"\n      ],\n      \"env\": {\n        \"DATABASE_URI\": \"${DATABASE_URI}\"\n      }\n    }\n  }\n}\n",
    "install": "claude mcp add postgres -e DATABASE_URI=${DATABASE_URI} -- npx -y enhanced-postgres-mcp-server@1.0.1",
    "envVars": [
      "DATABASE_URI"
    ]
  },
  {
    "id": "mcp-puppeteer",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "puppeteer",
    "title": "Puppeteer",
    "description": "Browser automation via Puppeteer.",
    "source": "https://www.npmjs.com/package/puppeteer-mcp-server",
    "license": "MIT",
    "tags": [
      "mcp",
      "browser",
      "web"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"puppeteer\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"puppeteer-mcp-server@0.7.2\"\n      ]\n    }\n  }\n}\n",
    "install": "claude mcp add puppeteer -- npx -y puppeteer-mcp-server@0.7.2",
    "envVars": []
  },
  {
    "id": "mcp-sentry",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "sentry",
    "title": "Sentry",
    "description": "Look up and triage errors and issues from Sentry.",
    "source": "https://www.npmjs.com/package/mcp-server-sentry",
    "license": "MIT",
    "tags": [
      "mcp",
      "observability",
      "api"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"sentry\": {\n      \"command\": \"uvx\",\n      \"args\": [\n        \"mcp-server-sentry==2025.1.14\",\n        \"--auth-token\",\n        \"${SENTRY_AUTH_TOKEN}\"\n      ]\n    }\n  }\n}\n",
    "install": "claude mcp add sentry -- uvx mcp-server-sentry==2025.1.14 --auth-token ${SENTRY_AUTH_TOKEN}",
    "envVars": [
      "SENTRY_AUTH_TOKEN"
    ]
  },
  {
    "id": "mcp-sequential-thinking",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "sequential-thinking",
    "title": "Sequential Thinking",
    "description": "Structured step-by-step reasoning scratchpad.",
    "source": "https://www.npmjs.com/package/@modelcontextprotocol/server-sequential-thinking",
    "license": "MIT",
    "tags": [
      "mcp",
      "reasoning"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"sequential-thinking\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"@modelcontextprotocol/server-sequential-thinking@2025.12.18\"\n      ]\n    }\n  }\n}\n",
    "install": "claude mcp add sequential-thinking -- npx -y @modelcontextprotocol/server-sequential-thinking@2025.12.18",
    "envVars": []
  },
  {
    "id": "mcp-slack",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "slack",
    "title": "Slack",
    "description": "Read channels and post messages to Slack.",
    "source": "https://www.npmjs.com/package/@modelcontextprotocol/server-slack",
    "license": "MIT",
    "tags": [
      "mcp",
      "chat",
      "api"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"slack\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"@modelcontextprotocol/server-slack@2025.4.25\"\n      ],\n      \"env\": {\n        \"SLACK_BOT_TOKEN\": \"${SLACK_BOT_TOKEN}\",\n        \"SLACK_TEAM_ID\": \"${SLACK_TEAM_ID}\"\n      }\n    }\n  }\n}\n",
    "install": "claude mcp add slack -e SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN} -e SLACK_TEAM_ID=${SLACK_TEAM_ID} -- npx -y @modelcontextprotocol/server-slack@2025.4.25",
    "envVars": [
      "SLACK_BOT_TOKEN",
      "SLACK_TEAM_ID"
    ]
  },
  {
    "id": "mcp-sqlite",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "sqlite",
    "title": "SQLite",
    "description": "Query and inspect a local SQLite database.",
    "source": "https://www.npmjs.com/package/mcp-server-sqlite",
    "license": "MIT",
    "tags": [
      "mcp",
      "database",
      "sql"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"sqlite\": {\n      \"command\": \"uvx\",\n      \"args\": [\n        \"mcp-server-sqlite==2025.4.25\",\n        \"--db-path\",\n        \"./data.db\"\n      ]\n    }\n  }\n}\n",
    "install": "claude mcp add sqlite -- uvx mcp-server-sqlite==2025.4.25 --db-path ./data.db",
    "envVars": []
  },
  {
    "id": "mcp-stripe",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "stripe",
    "title": "Stripe",
    "description": "Manage payments, customers, and invoices via Stripe.",
    "source": "https://www.npmjs.com/package/@stripe/mcp",
    "license": "MIT",
    "tags": [
      "mcp",
      "payments",
      "api"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"stripe\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"@stripe/mcp@0.3.3\",\n        \"--tools=all\"\n      ],\n      \"env\": {\n        \"STRIPE_SECRET_KEY\": \"${STRIPE_SECRET_KEY}\"\n      }\n    }\n  }\n}\n",
    "install": "claude mcp add stripe -e STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY} -- npx -y @stripe/mcp@0.3.3 --tools=all",
    "envVars": [
      "STRIPE_SECRET_KEY"
    ]
  },
  {
    "id": "mcp-supabase",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "supabase",
    "title": "Supabase",
    "description": "Manage a Supabase project: tables, SQL, edge functions.",
    "source": "https://www.npmjs.com/package/@supabase/mcp-server-supabase",
    "license": "MIT",
    "tags": [
      "mcp",
      "database",
      "api"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"supabase\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"@supabase/mcp-server-supabase@0.8.2\"\n      ],\n      \"env\": {\n        \"SUPABASE_ACCESS_TOKEN\": \"${SUPABASE_ACCESS_TOKEN}\"\n      }\n    }\n  }\n}\n",
    "install": "claude mcp add supabase -e SUPABASE_ACCESS_TOKEN=${SUPABASE_ACCESS_TOKEN} -- npx -y @supabase/mcp-server-supabase@0.8.2",
    "envVars": [
      "SUPABASE_ACCESS_TOKEN"
    ]
  },
  {
    "id": "mcp-tavily",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "tavily",
    "title": "Tavily",
    "description": "Web search and extraction optimized for LLMs.",
    "source": "https://www.npmjs.com/package/tavily-mcp",
    "license": "MIT",
    "tags": [
      "mcp",
      "web",
      "search",
      "api"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"tavily\": {\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"tavily-mcp@0.2.20\"\n      ],\n      \"env\": {\n        \"TAVILY_API_KEY\": \"${TAVILY_API_KEY}\"\n      }\n    }\n  }\n}\n",
    "install": "claude mcp add tavily -e TAVILY_API_KEY=${TAVILY_API_KEY} -- npx -y tavily-mcp@0.2.20",
    "envVars": [
      "TAVILY_API_KEY"
    ]
  },
  {
    "id": "mcp-time",
    "kind": "mcp",
    "configKind": "mcp",
    "name": "time",
    "title": "Time",
    "description": "Current time and timezone conversion utilities.",
    "source": "https://www.npmjs.com/package/mcp-server-time",
    "license": "MIT",
    "tags": [
      "mcp",
      "utility"
    ],
    "targetPath": ".mcp.json",
    "content": "{\n  \"mcpServers\": {\n    \"time\": {\n      \"command\": \"uvx\",\n      \"args\": [\n        \"mcp-server-time==2026.6.4\"\n      ]\n    }\n  }\n}\n",
    "install": "claude mcp add time -- uvx mcp-server-time==2026.6.4",
    "envVars": []
  }
];
