/**
 * GENERATED by scripts/sync-stars.mjs — do not edit by hand.
 * Curated directory of Skills / MCP / Tools repositories with synced star counts.
 * Source of truth: data/repo-directory.json. Refresh: `npm run sync:stars`.
 */
/* eslint-disable */
export const REPO_DIRECTORY_UPDATED = "2026-07-25T08:53:39.540Z";

export const REPO_DIRECTORY_ITEMS = [
  {
    "fullName": "openclaw/openclaw",
    "url": "https://github.com/openclaw/openclaw",
    "description": "Your own personal AI assistant. Any OS. Any Platform. The lobster way. 🦞",
    "stars": 384074,
    "kind": "skills",
    "collections": [
      "skill-platforms"
    ],
    "topics": [
      "coding"
    ],
    "note": "Assistant platform that ships skills as a core feature: bundled/managed/workspace skills, ClawHub skills registry (verified via README)"
  },
  {
    "fullName": "obra/superpowers",
    "url": "https://github.com/obra/superpowers",
    "description": "An agentic skills framework & software development methodology that works.",
    "stars": 260732,
    "kind": "skills",
    "collections": [
      "skill-collections"
    ],
    "topics": [
      "coding"
    ],
    "note": "Agentic skills framework and collection of Claude Code skills plus dev methodology"
  },
  {
    "fullName": "affaan-m/ECC",
    "url": "https://github.com/affaan-m/ECC",
    "description": "The agent harness performance optimization system. Skills, instincts, memory, security, and research-first development for Claude Code, Codex, Opencode, Cursor and beyond.",
    "stars": 233019,
    "kind": "skills",
    "collections": [
      "skill-platforms"
    ],
    "topics": [
      "coding"
    ],
    "note": "Agent harness that ships skills (plus instincts/memory) for Claude Code, Codex, Opencode, Cursor"
  },
  {
    "fullName": "NousResearch/hermes-agent",
    "url": "https://github.com/NousResearch/hermes-agent",
    "description": "The agent that grows with you",
    "stars": 220174,
    "kind": "skills",
    "collections": [
      "skill-platforms"
    ],
    "topics": [
      "coding"
    ],
    "note": "Agent with built-in skill creation/self-improvement loop, compatible with agentskills.io open standard (verified via README)"
  },
  {
    "fullName": "multica-ai/andrej-karpathy-skills",
    "url": "https://github.com/multica-ai/andrej-karpathy-skills",
    "description": "A single CLAUDE.md file to improve Claude Code behavior, derived from Andrej Karpathy's observations on LLM coding pitfalls.",
    "stars": 196148,
    "kind": "skills",
    "collections": [
      "single-skills"
    ],
    "topics": [
      "coding"
    ],
    "note": "Claude Code behavior pack named as skills; technically a single CLAUDE.md prompt file rather than SKILL.md"
  },
  {
    "fullName": "mattpocock/skills",
    "url": "https://github.com/mattpocock/skills",
    "description": "Skills for Real Engineers. Straight from my .agents directory.",
    "stars": 187368,
    "kind": "skills",
    "collections": [
      "skill-collections"
    ],
    "topics": [
      "coding"
    ],
    "note": "Personal collection of engineering skills from author's .agents directory"
  },
  {
    "fullName": "anthropics/skills",
    "url": "https://github.com/anthropics/skills",
    "description": "Public repository for Agent Skills",
    "stars": 164032,
    "kind": "skills",
    "collections": [
      "official-skills",
      "skill-collections"
    ],
    "topics": [
      "general"
    ],
    "note": "Anthropic's official public Agent Skills repository"
  },
  {
    "fullName": "firecrawl/firecrawl",
    "url": "https://github.com/firecrawl/firecrawl",
    "description": "The API to search, scrape, and interact with the web at scale. 🔥",
    "stars": 155719,
    "kind": "tools",
    "collections": [
      "agent-tools"
    ],
    "topics": [
      "coding"
    ],
    "note": "Web search/scrape API built for LLM-ready data; core web capability for agents, ships official MCP server"
  },
  {
    "fullName": "Shubhamsaboo/awesome-llm-apps",
    "url": "https://github.com/Shubhamsaboo/awesome-llm-apps",
    "description": "100+ AI Agents, Agent Skills and RAG Apps - Free and Open Source.",
    "stars": 127472,
    "kind": "lists",
    "collections": [
      "awesome-skills"
    ],
    "topics": [
      "coding"
    ],
    "note": "Broad LLM apps list but explicitly includes Agent Skills as a headline content category"
  },
  {
    "fullName": "garrytan/gstack",
    "url": "https://github.com/garrytan/gstack",
    "description": "Use Garry Tan's exact Claude Code setup: 23 opinionated tools that serve as CEO, Designer, Eng Manager, Release Manager, Doc Engineer, and QA",
    "stars": 124208,
    "kind": "skills",
    "collections": [
      "skill-platforms"
    ],
    "topics": [
      "coding"
    ],
    "note": "Claude Code setup that ships skills as a real feature: SKILL.md, SKILL.md.tmpl, browser-skills/, skillify/ (verified via repo tree)"
  },
  {
    "fullName": "nextlevelbuilder/ui-ux-pro-max-skill",
    "url": "https://github.com/nextlevelbuilder/ui-ux-pro-max-skill",
    "description": "An AI SKILL that provide design intelligence for building professional UI/UX multiple platforms",
    "stars": 109898,
    "kind": "skills",
    "collections": [
      "single-skills"
    ],
    "topics": [
      "creative"
    ],
    "note": "A published AI skill providing UI/UX design intelligence"
  },
  {
    "fullName": "browser-use/browser-use",
    "url": "https://github.com/browser-use/browser-use",
    "description": "🌐 Make websites accessible for AI agents. Automate tasks online with ease.",
    "stars": 106684,
    "kind": "tools",
    "collections": [
      "agent-tools"
    ],
    "topics": [
      "coding"
    ],
    "note": "Browser-use toolkit giving AI agents web automation capability"
  },
  {
    "fullName": "Graphify-Labs/graphify",
    "url": "https://github.com/Graphify-Labs/graphify",
    "description": "Turn any codebase, with its docs, SQL schemas, configs, and PDFs, into a queryable knowledge graph. A /graphify skill for Claude Code, Cursor, Codex, and Gemini CLI: local deterministic AST parsing, every edge explained, no vector store.",
    "stars": 95454,
    "kind": "skills",
    "collections": [
      "single-skills"
    ],
    "topics": [
      "coding"
    ],
    "note": "A /graphify skill for Claude Code, Cursor, Codex, and Gemini CLI (codebase knowledge graph)"
  },
  {
    "fullName": "JuliusBrussee/caveman",
    "url": "https://github.com/JuliusBrussee/caveman",
    "description": "🪨 why use many token when few token do trick — Claude Code skill that cuts 65% of tokens by talking like caveman",
    "stars": 92840,
    "kind": "skills",
    "collections": [
      "single-skills"
    ],
    "topics": [
      "coding"
    ],
    "note": "Claude Code skill that reduces token usage via terse output"
  },
  {
    "fullName": "punkpeye/awesome-mcp-servers",
    "url": "https://github.com/punkpeye/awesome-mcp-servers",
    "description": "A collection of MCP servers.",
    "stars": 91374,
    "kind": "lists",
    "collections": [
      "awesome-mcp"
    ],
    "topics": [
      "coding"
    ],
    "note": "Curated list of MCP servers"
  },
  {
    "fullName": "DietrichGebert/ponytail",
    "url": "https://github.com/DietrichGebert/ponytail",
    "description": "Makes your AI agent think like the laziest senior dev in the room. The best code is the code you never wrote.",
    "stars": 89131,
    "kind": "skills",
    "collections": [
      "single-skills"
    ],
    "topics": [
      "coding"
    ],
    "note": "Published agent behavior skill (lazy-senior-dev minimalism) installed as a skill/plugin for coding agents"
  },
  {
    "fullName": "modelcontextprotocol/servers",
    "url": "https://github.com/modelcontextprotocol/servers",
    "description": "Model Context Protocol Servers",
    "stars": 88875,
    "kind": "mcp",
    "collections": [
      "official-mcp"
    ],
    "topics": [
      "coding"
    ],
    "note": "Official MCP reference server collection (modelcontextprotocol org)"
  },
  {
    "fullName": "nexu-io/open-design",
    "url": "https://github.com/nexu-io/open-design",
    "description": "🎨 The open-source Claude Design alternative. 🖥️ Local-first desktop app. 🖼️ Your coding agent becomes the design engine: prototypes, landing pages, dashboards, slides, images & video — real files, HTML/PDF/PPTX/MP4 export. 🤖 Claude Code / Codex / Cursor / Gemini / OpenCode / Qwen & 20+ CLIs via BYOK.",
    "stars": 81403,
    "kind": "skills",
    "collections": [
      "creative-media"
    ],
    "topics": [
      "creative"
    ],
    "note": "Agent-driven design engine: slides, images, video, landing pages with PDF/PPTX/MP4 export"
  },
  {
    "fullName": "addyosmani/agent-skills",
    "url": "https://github.com/addyosmani/agent-skills",
    "description": "Production-grade engineering skills for AI coding agents.",
    "stars": 80267,
    "kind": "skills",
    "collections": [
      "skill-collections"
    ],
    "topics": [
      "coding"
    ],
    "note": "Production-grade engineering skills for AI coding agents"
  },
  {
    "fullName": "ComposioHQ/awesome-claude-skills",
    "url": "https://github.com/ComposioHQ/awesome-claude-skills",
    "description": "A curated list of awesome Claude Skills, resources, and tools for customizing Claude AI workflows",
    "stars": 70260,
    "kind": "lists",
    "collections": [
      "awesome-skills",
      "skill-collections"
    ],
    "topics": [
      "general"
    ],
    "note": "Curated list of Claude Skills and tooling"
  },
  {
    "fullName": "Leonxlnx/taste-skill",
    "url": "https://github.com/Leonxlnx/taste-skill",
    "description": "Taste-Skill - gives your AI good taste. stops the AI from generating boring, generic slop",
    "stars": 67402,
    "kind": "skills",
    "collections": [
      "single-skills"
    ],
    "topics": [
      "creative"
    ],
    "note": "Single published skill giving AI design taste"
  },
  {
    "fullName": "headroomlabs-ai/headroom",
    "url": "https://github.com/headroomlabs-ai/headroom",
    "description": "Compress tool outputs, logs, files, and RAG chunks before they reach the LLM. 20% fewer tokens for coding agents, 60-95% fewer tokens for JSON, same answers. Library, proxy, MCP server.",
    "stars": 62277,
    "kind": "mcp",
    "collections": [
      "mcp-infra"
    ],
    "topics": [
      "coding"
    ],
    "note": "Tool-output/context compression shipped as library, proxy, and MCP server — sits in the agent tool pipeline"
  },
  {
    "fullName": "mem0ai/mem0",
    "url": "https://github.com/mem0ai/mem0",
    "description": "Universal memory layer for AI Agents",
    "stars": 61653,
    "kind": "tools",
    "collections": [
      "agent-tools"
    ],
    "topics": [
      "coding"
    ],
    "note": "Memory layer giving agents persistent-memory capability; ships OpenMemory MCP"
  },
  {
    "fullName": "upstash/context7",
    "url": "https://github.com/upstash/context7",
    "description": "Context7 Platform -- Up-to-date code documentation for LLMs and AI code editors",
    "stars": 59713,
    "kind": "mcp",
    "collections": [
      "mcp-servers"
    ],
    "topics": [
      "coding"
    ],
    "note": "Primarily known as the Context7 MCP server serving up-to-date library docs to agents"
  },
  {
    "fullName": "zylon-ai/private-gpt",
    "url": "https://github.com/zylon-ai/private-gpt",
    "description": "Complete API layer for private AI applications on local models: RAG, skills, tools, MCP, text-to-sql, and more. Works with any OpenAI-compatible inference server.",
    "stars": 57367,
    "kind": "skills",
    "collections": [
      "skill-platforms"
    ],
    "topics": [
      "coding"
    ],
    "note": "Verified README: ships Skills as a first-class agent feature (Agents | Skills checkmark in feature table)"
  },
  {
    "fullName": "mvanhorn/last30days-skill",
    "url": "https://github.com/mvanhorn/last30days-skill",
    "description": "AI agent skill that researches any topic across Reddit, X, YouTube, HN, Polymarket, and the web - then synthesizes a grounded summary",
    "stars": 53492,
    "kind": "skills",
    "collections": [
      "single-skills",
      "research-academic"
    ],
    "topics": [
      "research"
    ],
    "note": "Single AI agent research skill (Reddit/X/YouTube/HN synthesis)"
  },
  {
    "fullName": "VoltAgent/awesome-openclaw-skills",
    "url": "https://github.com/VoltAgent/awesome-openclaw-skills",
    "description": "The awesome collection of OpenClaw skills. 5,400+ skills filtered and categorized from the official OpenClaw Skills Registry.🦞",
    "stars": 51504,
    "kind": "lists",
    "collections": [
      "awesome-skills",
      "skill-collections"
    ],
    "topics": [
      "general"
    ],
    "note": "Curated collection of 5,400+ OpenClaw skills"
  },
  {
    "fullName": "hesreallyhim/awesome-claude-code",
    "url": "https://github.com/hesreallyhim/awesome-claude-code",
    "description": "A hand-picked collection of the finest of resources for the most awesome of agents, Claude Code, the undisputed champion of coding companions, from the unstoppable team at Anthropic PBC. A delectable showcase of top tier skills, ambidextrous agents, scintillating status lines, top notch developer tooling, and also we have plugins",
    "stars": 50883,
    "kind": "lists",
    "collections": [
      "awesome-skills"
    ],
    "topics": [
      "coding"
    ],
    "note": "Curated Claude Code resources explicitly including skills and plugins"
  },
  {
    "fullName": "pbakaus/impeccable",
    "url": "https://github.com/pbakaus/impeccable",
    "description": "The design language that makes your AI harness better at design.",
    "stars": 49796,
    "kind": "skills",
    "collections": [
      "single-skills"
    ],
    "topics": [
      "creative"
    ],
    "note": "README: '1 skill, 23 commands' — design skill for AI coding agents, successor to Anthropic's frontend-design skill, with CLI installer and detector rules"
  },
  {
    "fullName": "ChromeDevTools/chrome-devtools-mcp",
    "url": "https://github.com/ChromeDevTools/chrome-devtools-mcp",
    "description": "Chrome DevTools for coding agents",
    "stars": 47565,
    "kind": "mcp",
    "collections": [
      "official-mcp"
    ],
    "topics": [
      "coding"
    ],
    "note": "Vendor-official (Chrome team) MCP server exposing DevTools to agents"
  },
  {
    "fullName": "jeecgboot/JeecgBoot",
    "url": "https://github.com/jeecgboot/JeecgBoot",
    "description": "【低代码迈入v2.0时代，一句话即可生成整个系统】企业级AI低代码平台，一键生成前后端代码甚至整个系统。 AI Skills 一句话画流程、设计表单、生成报表、大屏。内置 AI应用平台涵盖：AI聊天、知识库、流程编排、MCP插件等，兼容主流大模型。引领AI低代码「Skills 生成 → 在线配置 → 代码生成 → 手工合并->AI修改」开发模式，解决 Java 项目 90% 重复工作，提高效率又不失灵活。",
    "stars": 47181,
    "kind": "skills",
    "collections": [
      "skill-platforms"
    ],
    "topics": [
      "coding"
    ],
    "note": "Low-code platform that headlines an 'AI Skills' feature (Skills-driven generation mode); repo topics include skills, claude-code, codex — ships skills as a real feature"
  },
  {
    "fullName": "zhayujie/CowAgent",
    "url": "https://github.com/zhayujie/CowAgent",
    "description": "Open-source super AI assistant & Agent Harness. Plans tasks, runs tools and skills, self-evolves with memory and knowledge. Multi-model, multi-channel. Lightweight, extensible, one-line install. (formerly chatgpt-on-wechat)",
    "stars": 46115,
    "kind": "skills",
    "collections": [
      "skill-platforms"
    ],
    "topics": [
      "coding"
    ],
    "note": "Agent harness whose description explicitly ships skills as a feature ('runs tools and skills')"
  },
  {
    "fullName": "sickn33/agentic-awesome-skills",
    "url": "https://github.com/sickn33/agentic-awesome-skills",
    "description": "AAS Core is the local, agent-first control plane for complete catalog discovery, agent-owned selection, stack validation, and planning, backed by 1,987+ agentic skills. Includes CLI, local MCP, catalog, plugins, and Workbench.",
    "stars": 43869,
    "kind": "skills",
    "collections": [
      "skill-collections"
    ],
    "topics": [
      "general"
    ],
    "note": "Catalog of 1,987+ agentic skills plus CLI/MCP control plane for discovery and selection"
  },
  {
    "fullName": "kepano/obsidian-skills",
    "url": "https://github.com/kepano/obsidian-skills",
    "description": "Agent skills for Obsidian. Teach your agent to use Obsidian CLI and open formats including Markdown, Bases, JSON Canvas.",
    "stars": 43230,
    "kind": "skills",
    "collections": [
      "skill-collections",
      "life-personal"
    ],
    "topics": [
      "life"
    ],
    "note": "Agent skills for Obsidian CLI and open formats"
  },
  {
    "fullName": "calesthio/OpenMontage",
    "url": "https://github.com/calesthio/OpenMontage",
    "description": "World's first open-source, agentic video production system. 12 production pipelines, 100+ tools, 700+ agent skill and production-knowledge files. Turn your AI coding assistant into a full video production studio.",
    "stars": 42078,
    "kind": "skills",
    "collections": [
      "skill-platforms",
      "creative-media"
    ],
    "topics": [
      "creative"
    ],
    "note": "Video production system shipping 700+ agent skill files as a core feature"
  },
  {
    "fullName": "multica-ai/multica",
    "url": "https://github.com/multica-ai/multica",
    "description": "The open-source managed agents platform. Turn coding agents into real teammates — assign tasks, track progress, compound skills.",
    "stars": 41979,
    "kind": "skills",
    "collections": [
      "skill-platforms"
    ],
    "topics": [
      "coding"
    ],
    "note": "Managed-agents platform; description headlines 'compound skills' — ships a reusable skill library as a core feature"
  },
  {
    "fullName": "coreyhaines31/marketingskills",
    "url": "https://github.com/coreyhaines31/marketingskills",
    "description": "Marketing skills for Claude Code and AI agents. CRO, copywriting, SEO, analytics, and growth engineering.",
    "stars": 41612,
    "kind": "skills",
    "collections": [
      "skill-collections",
      "marketing-seo"
    ],
    "topics": [
      "marketing"
    ],
    "note": "Marketing skills (CRO, SEO, copywriting) for Claude Code and AI agents"
  },
  {
    "fullName": "danny-avila/LibreChat",
    "url": "https://github.com/danny-avila/LibreChat",
    "description": "Enhanced ChatGPT Clone: Features Agents, MCP, Skills, DeepSeek, Anthropic, AWS, OpenAI, Responses API, Azure, Groq, o1, GPT-5, Mistral, OpenRouter, Vertex AI, Gemini, Artifacts, AI model switching, message search, Code Interpreter, langchain, DALL-E-3, OpenAPI Actions, Functions, Secure Multi-User Auth, Presets, open-source for self-hosting. Active",
    "stars": 41259,
    "kind": "skills",
    "collections": [
      "skill-platforms"
    ],
    "topics": [
      "coding"
    ],
    "note": "Chat platform whose description explicitly ships Skills as a feature alongside Agents/MCP"
  },
  {
    "fullName": "hugohe3/ppt-master",
    "url": "https://github.com/hugohe3/ppt-master",
    "description": "AI turns documents or topics into real, native PowerPoint decks—with native shapes, transitions and animations, data-backed charts and tables on demand, audio narration from speaker notes, and support for your own .pptx templates. · by Hugo He",
    "stars": 41004,
    "kind": "skills",
    "collections": [
      "single-skills"
    ],
    "topics": [
      "office",
      "creative"
    ],
    "note": "Verified README: distributed as a skill (skills/ppt-master/SKILL.md), installable via npx skills add and Claude Code plugin marketplace"
  },
  {
    "fullName": "Imbad0202/academic-research-skills",
    "url": "https://github.com/Imbad0202/academic-research-skills",
    "description": "Academic Research Skills for Claude Code: research → write → review → revise → finalize",
    "stars": 39436,
    "kind": "skills",
    "collections": [
      "skill-collections",
      "research-academic"
    ],
    "topics": [
      "research"
    ],
    "note": "Academic research skills for Claude Code (research/write/review pipeline)"
  },
  {
    "fullName": "vercel-labs/agent-browser",
    "url": "https://github.com/vercel-labs/agent-browser",
    "description": "Browser automation CLI for AI agents",
    "stars": 39166,
    "kind": "tools",
    "collections": [
      "agent-tools"
    ],
    "topics": [
      "coding"
    ],
    "note": "Browser automation CLI purpose-built for AI agents"
  },
  {
    "fullName": "wshobson/agents",
    "url": "https://github.com/wshobson/agents",
    "description": "Multi-harness agentic plugin marketplace for Claude Code, Codex CLI, Cursor, OpenCode, GitHub Copilot, and Gemini CLI",
    "stars": 38207,
    "kind": "skills",
    "collections": [
      "skill-platforms",
      "skill-collections"
    ],
    "topics": [
      "general"
    ],
    "note": "Multi-harness plugin marketplace (agents/commands/skills) for Claude Code, Codex, Cursor, Gemini CLI"
  },
  {
    "fullName": "github/awesome-copilot",
    "url": "https://github.com/github/awesome-copilot",
    "description": "Community-contributed instructions, agents, skills, and configurations to help you make the most of GitHub Copilot.",
    "stars": 37018,
    "kind": "lists",
    "collections": [
      "awesome-skills"
    ],
    "topics": [
      "coding"
    ],
    "note": "Community collection of Copilot instructions, agents, and skills"
  },
  {
    "fullName": "microsoft/playwright-mcp",
    "url": "https://github.com/microsoft/playwright-mcp",
    "description": "Playwright MCP server",
    "stars": 35477,
    "kind": "mcp",
    "collections": [
      "official-mcp"
    ],
    "topics": [
      "coding"
    ],
    "note": "Vendor-official (Microsoft) Playwright browser MCP server"
  },
  {
    "fullName": "DeusData/codebase-memory-mcp",
    "url": "https://github.com/DeusData/codebase-memory-mcp",
    "description": "High-performance code intelligence MCP server. Indexes codebases into a persistent knowledge graph — average repo in milliseconds. 158 languages, sub-ms queries, 99% fewer tokens. Single static binary, zero dependencies.",
    "stars": 35131,
    "kind": "mcp",
    "collections": [
      "mcp-servers"
    ],
    "topics": [
      "coding"
    ],
    "note": "Code-intelligence MCP server indexing codebases into a knowledge graph"
  },
  {
    "fullName": "anthropics/financial-services",
    "url": "https://github.com/anthropics/financial-services",
    "description": "",
    "stars": 33769,
    "kind": "skills",
    "collections": [
      "official-skills"
    ],
    "topics": [
      "coding"
    ],
    "note": "README: official Anthropic reference agents, skills, and vertical plugins for financial services"
  },
  {
    "fullName": "anthropics/claude-plugins-official",
    "url": "https://github.com/anthropics/claude-plugins-official",
    "description": "Official, Anthropic-managed directory of high quality Claude Code Plugins.",
    "stars": 32628,
    "kind": "skills",
    "collections": [
      "official-skills"
    ],
    "topics": [
      "coding"
    ],
    "note": "Official Anthropic-managed Claude Code plugin directory/marketplace (plugins bundle skills)"
  },
  {
    "fullName": "Leey21/awesome-ai-research-writing",
    "url": "https://github.com/Leey21/awesome-ai-research-writing",
    "description": "Elevate your AI research writing, no more tedious polishing ✨",
    "stars": 32064,
    "kind": "lists",
    "collections": [
      "awesome-skills"
    ],
    "topics": [
      "research",
      "writing"
    ],
    "note": "README: curated prompt templates plus agent skills and tutorials for research writing"
  },
  {
    "fullName": "K-Dense-AI/scientific-agent-skills",
    "url": "https://github.com/K-Dense-AI/scientific-agent-skills",
    "description": "Turn any AI agent into an AI Scientist. The #1 Agent Skills library for science, used by 160,000+ scientists worldwide. 148 ready-to-use skills plus 100+ scientific databases covering biology, chemistry, medicine, and drug discovery. Compatible with Cursor, Claude Code, Codex, Pi, Antigravity, and the open Agent Skills standard.",
    "stars": 31700,
    "kind": "skills",
    "collections": [
      "skill-collections",
      "research-academic"
    ],
    "topics": [
      "research"
    ],
    "note": "148 agent skills for science, Agent Skills standard compatible"
  },
  {
    "fullName": "github/github-mcp-server",
    "url": "https://github.com/github/github-mcp-server",
    "description": "GitHub's official MCP Server",
    "stars": 31696,
    "kind": "mcp",
    "collections": [
      "official-mcp"
    ],
    "topics": [
      "coding"
    ],
    "note": "GitHub's vendor-official MCP server"
  },
  {
    "fullName": "hesamsheikh/awesome-openclaw-usecases",
    "url": "https://github.com/hesamsheikh/awesome-openclaw-usecases",
    "description": "A community collection of OpenClaw use cases for making life easier.",
    "stars": 31531,
    "kind": "skills",
    "collections": [
      "life-personal"
    ],
    "topics": [
      "life"
    ],
    "note": "OpenClaw use-case collection for personal-life automation; use cases, not packaged skills"
  },
  {
    "fullName": "Yuan1z0825/nature-skills",
    "url": "https://github.com/Yuan1z0825/nature-skills",
    "description": "符合nature论文学术表达和科研绘图的Skill",
    "stars": 31045,
    "kind": "skills",
    "collections": [
      "skill-collections",
      "research-academic"
    ],
    "topics": [
      "research"
    ],
    "note": "README: 18 research skills installable in Claude Code/Codex/OpenClaw/OpenCode"
  },
  {
    "fullName": "blader/humanizer",
    "url": "https://github.com/blader/humanizer",
    "description": "Agent skill that removes signs of AI-generated writing from text",
    "stars": 30920,
    "kind": "skills",
    "collections": [
      "single-skills",
      "writing-content"
    ],
    "topics": [
      "writing"
    ],
    "note": "Single agent skill that de-AI-ifies writing"
  },
  {
    "fullName": "googleworkspace/cli",
    "url": "https://github.com/googleworkspace/cli",
    "description": "Google Workspace CLI — one command-line tool for Drive, Gmail, Calendar, Sheets, Docs, Chat, Admin, and more. Dynamically built from Google Discovery Service. Includes AI agent skills.",
    "stars": 29994,
    "kind": "skills",
    "collections": [
      "skill-platforms",
      "office-suite"
    ],
    "topics": [
      "office"
    ],
    "note": "Google Workspace CLI that ships AI agent skills as a feature"
  },
  {
    "fullName": "vercel-labs/agent-skills",
    "url": "https://github.com/vercel-labs/agent-skills",
    "description": "Vercel's official collection of agent skills",
    "stars": 29459,
    "kind": "skills",
    "collections": [
      "skill-collections"
    ],
    "topics": [
      "coding"
    ],
    "note": "Vercel's official agent skills collection"
  },
  {
    "fullName": "ComposioHQ/composio",
    "url": "https://github.com/ComposioHQ/composio",
    "description": "Composio powers 1000+ toolkits, tool search, context management, authentication, and a sandboxed workbench to help you build AI agents that turn intent into action.",
    "stars": 29363,
    "kind": "tools",
    "collections": [
      "agent-tools"
    ],
    "topics": [
      "coding"
    ],
    "note": "1000+ authenticated toolkits/tool search for agents"
  },
  {
    "fullName": "getzep/graphiti",
    "url": "https://github.com/getzep/graphiti",
    "description": "Build Real-Time Knowledge Graphs for AI Agents",
    "stars": 29183,
    "kind": "tools",
    "collections": [
      "agent-tools"
    ],
    "topics": [
      "coding"
    ],
    "note": "Real-time knowledge-graph memory for agents; includes MCP server"
  },
  {
    "fullName": "VoltAgent/awesome-agent-skills",
    "url": "https://github.com/VoltAgent/awesome-agent-skills",
    "description": "A curated collection of 1000+ agent skills from official dev teams and the community, compatible with Claude Code, Codex, Gemini CLI, Cursor, and more.",
    "stars": 28883,
    "kind": "lists",
    "collections": [
      "awesome-skills",
      "skill-collections"
    ],
    "topics": [
      "general"
    ],
    "note": "Curated 1000+ agent skills for Claude Code/Codex/Gemini CLI/Cursor"
  },
  {
    "fullName": "alchaincyf/nuwa-skill",
    "url": "https://github.com/alchaincyf/nuwa-skill",
    "description": "你想蒸馏的下一个员工，何必是同事。蒸馏任何人的思维方式——心智模型、决策启发式、表达DNA。Distill how anyone thinks.",
    "stars": 28728,
    "kind": "skills",
    "collections": [
      "single-skills"
    ],
    "topics": [
      "writing",
      "life"
    ],
    "note": "Agent skill that distills a person's thinking/expression style"
  },
  {
    "fullName": "volcengine/OpenViking",
    "url": "https://github.com/volcengine/OpenViking",
    "description": "Self-evolving Context Database for AI Agents. Unify Agent Memory, Knowledge RAG and Skills.",
    "stars": 27204,
    "kind": "tools",
    "collections": [
      "agent-tools"
    ],
    "topics": [
      "coding"
    ],
    "note": "Context database unifying agent memory, RAG, and skills — capability layer for agents"
  },
  {
    "fullName": "vercel-labs/skills",
    "url": "https://github.com/vercel-labs/skills",
    "description": "The open agent skills tool - npx skills",
    "stars": 27164,
    "kind": "skills",
    "collections": [
      "skill-platforms"
    ],
    "topics": [
      "coding"
    ],
    "note": "npx skills — the open agent-skills installer/CLI tooling"
  },
  {
    "fullName": "oraios/serena",
    "url": "https://github.com/oraios/serena",
    "description": "A powerful MCP toolkit for coding, providing semantic retrieval and editing capabilities  - the IDE for your agent",
    "stars": 26867,
    "kind": "mcp",
    "collections": [
      "mcp-servers"
    ],
    "topics": [
      "coding"
    ],
    "note": "MCP server/toolkit providing semantic code retrieval and editing tools to agents"
  },
  {
    "fullName": "charmbracelet/crush",
    "url": "https://github.com/charmbracelet/crush",
    "description": "Glamourous agentic coding for all 💘",
    "stars": 26833,
    "kind": "skills",
    "collections": [
      "skill-platforms"
    ],
    "topics": [
      "coding"
    ],
    "note": "Coding-agent CLI that ships builtin skills plus skill discovery/disable config as a first-class feature (README verified)"
  },
  {
    "fullName": "PrefectHQ/fastmcp",
    "url": "https://github.com/PrefectHQ/fastmcp",
    "description": "🚀 The fast, Pythonic way to build MCP servers and clients.",
    "stars": 26829,
    "kind": "mcp",
    "collections": [
      "mcp-frameworks"
    ],
    "topics": [
      "coding"
    ],
    "note": "Leading Python framework for building MCP servers and clients"
  },
  {
    "fullName": "mukul975/Anthropic-Cybersecurity-Skills",
    "url": "https://github.com/mukul975/Anthropic-Cybersecurity-Skills",
    "description": "817 structured cybersecurity skills for AI agents · Mapped to 6 frameworks: MITRE ATT&CK, NIST CSF 2.0, MITRE ATLAS, D3FEND, NIST AI RMF & MITRE F3 (Fight Fraud) · agentskills.io standard · Works with Claude Code, GitHub Copilot, Codex CLI, Cursor, Gemini CLI & 20+ platforms · 29 security domains · Apache 2.0",
    "stars": 26516,
    "kind": "skills",
    "collections": [
      "skill-collections",
      "agent-tools"
    ],
    "topics": [
      "coding"
    ],
    "note": "817 cybersecurity agent skills, agentskills.io standard"
  },
  {
    "fullName": "MadsLorentzen/ai-job-search",
    "url": "https://github.com/MadsLorentzen/ai-job-search",
    "description": "The job search that runs on your machine. AI job application framework built on Claude Code: evaluate postings, tailor CVs, write cover letters, prep interviews. Fork it and own it.",
    "stars": 26494,
    "kind": "skills",
    "collections": [
      "skill-platforms"
    ],
    "topics": [
      "business"
    ],
    "note": "Job-hunt domain, but README verified: ships cross-agent portal-search skills (.agents/skills) usable in Claude Code/Codex/Gemini CLI"
  },
  {
    "fullName": "zarazhangrui/frontend-slides",
    "url": "https://github.com/zarazhangrui/frontend-slides",
    "description": "Create beautiful slides on the web using a coding agent's frontend skills",
    "stars": 26312,
    "kind": "skills",
    "collections": [
      "single-skills",
      "creative-media"
    ],
    "topics": [
      "creative"
    ],
    "note": "Topics confirm claude-skill; slide-generation skill"
  },
  {
    "fullName": "OthmanAdi/planning-with-files",
    "url": "https://github.com/OthmanAdi/planning-with-files",
    "description": "Persistent file-based planning for AI coding agents and long-running tasks. Crash-proof markdown plans, session recovery after /clear and compaction, per-turn re-injection against context rot, deterministic completion gate. Manus-style. Claude Code, Codex, Cursor, Kiro, OpenCode and 60+ agents via the Agent Skills standard.",
    "stars": 25724,
    "kind": "skills",
    "collections": [
      "single-skills"
    ],
    "topics": [
      "coding"
    ],
    "note": "Planning skill published via the Agent Skills standard for 60+ agents"
  },
  {
    "fullName": "flipped-aurora/gin-vue-admin",
    "url": "https://github.com/flipped-aurora/gin-vue-admin",
    "description": "🚀Vite+Vue3+Gin拥有AI辅助的基础开发平台，企业级业务AI+开发解决方案，内置mcp辅助服务，内置skills管理，支持TS和JS混用。它集成了JWT鉴权、权限管理、动态路由、显隐可控组件、分页封装、多点登录拦截、资源权限、上传下载、代码生成器、表单生成器和可配置的导入导出等开发必备功能。",
    "stars": 24871,
    "kind": "skills",
    "collections": [
      "skill-platforms"
    ],
    "topics": [
      "coding"
    ],
    "note": "Admin dev platform, but description explicitly ships built-in skills management (内置skills管理) as a feature"
  },
  {
    "fullName": "ahujasid/blender-mcp",
    "url": "https://github.com/ahujasid/blender-mcp",
    "description": "Open-source MCP to use Blender with any LLM",
    "stars": 24791,
    "kind": "mcp",
    "collections": [
      "mcp-servers"
    ],
    "topics": [
      "coding"
    ],
    "note": "MCP server connecting Blender to any LLM"
  },
  {
    "fullName": "phuryn/pm-skills",
    "url": "https://github.com/phuryn/pm-skills",
    "description": "PM Skills Marketplace: 100+ agentic skills, commands, and plugins — from discovery to strategy, execution, launch, and growth.",
    "stars": 24427,
    "kind": "skills",
    "collections": [
      "skill-collections",
      "business-pm"
    ],
    "topics": [
      "business"
    ],
    "note": "PM Skills Marketplace: 100+ agentic skills/commands/plugins"
  },
  {
    "fullName": "openai/skills",
    "url": "https://github.com/openai/skills",
    "description": "Skills Catalog for Codex",
    "stars": 24158,
    "kind": "skills",
    "collections": [
      "official-skills"
    ],
    "topics": [
      "coding"
    ],
    "note": "Official OpenAI Skills Catalog for Codex"
  },
  {
    "fullName": "JimLiu/baoyu-skills",
    "url": "https://github.com/JimLiu/baoyu-skills",
    "description": "",
    "stars": 24134,
    "kind": "skills",
    "collections": [
      "skill-collections",
      "writing-content"
    ],
    "topics": [
      "writing"
    ],
    "note": "Empty description; topics verified: agent-skills, claude-skills, codex-skills, openclaw-skills"
  },
  {
    "fullName": "modelcontextprotocol/python-sdk",
    "url": "https://github.com/modelcontextprotocol/python-sdk",
    "description": "The official Python SDK for Model Context Protocol servers and clients",
    "stars": 23717,
    "kind": "mcp",
    "collections": [
      "official-mcp"
    ],
    "topics": [
      "coding"
    ],
    "note": "Official MCP Python SDK"
  },
  {
    "fullName": "browserbase/stagehand",
    "url": "https://github.com/browserbase/stagehand",
    "description": "The SDK For Browser Agents",
    "stars": 23630,
    "kind": "tools",
    "collections": [
      "agent-tools"
    ],
    "topics": [
      "coding"
    ],
    "note": "SDK giving agents browser-automation capability"
  },
  {
    "fullName": "agentskills/agentskills",
    "url": "https://github.com/agentskills/agentskills",
    "description": "Specification and documentation for Agent Skills",
    "stars": 23444,
    "kind": "skills",
    "collections": [
      "official-skills"
    ],
    "topics": [
      "coding"
    ],
    "note": "The Agent Skills specification and documentation"
  },
  {
    "fullName": "alirezarezvani/claude-skills",
    "url": "https://github.com/alirezarezvani/claude-skills",
    "description": "345 Claude Code skills & agent skills & plugins (30+ Agents, 70+ custom commands, 330+ skills, customizable references, scripts)for Claude Code, Codex, Gemini CLI, Cursor, and 8 more coding agents — engineering, marketing, product, compliance, C-level advisory, research, business operations, commercial & finance, and your daily productivity skills.",
    "stars": 23157,
    "kind": "skills",
    "collections": [
      "skill-collections"
    ],
    "topics": [
      "general"
    ],
    "note": "345 Claude Code / agent skills and plugins for 8+ agents"
  },
  {
    "fullName": "czlonkowski/n8n-mcp",
    "url": "https://github.com/czlonkowski/n8n-mcp",
    "description": "A MCP for Claude Desktop / Claude Code / Windsurf / Cursor to build n8n workflows for you",
    "stars": 22398,
    "kind": "mcp",
    "collections": [
      "mcp-servers"
    ],
    "topics": [
      "coding"
    ],
    "note": "MCP server that lets agents build n8n workflows"
  },
  {
    "fullName": "op7418/guizang-ppt-skill",
    "url": "https://github.com/op7418/guizang-ppt-skill",
    "description": "AI-agent Skill for generating polished HTML slide decks: editorial magazine and Swiss layouts, image prompts, social covers, and a WebGL/low-power presentation runtime.",
    "stars": 22323,
    "kind": "skills",
    "collections": [
      "single-skills",
      "creative-media"
    ],
    "topics": [
      "creative"
    ],
    "note": "AI-agent skill for HTML slide decks"
  },
  {
    "fullName": "iOfficeAI/OfficeCLI",
    "url": "https://github.com/iOfficeAI/OfficeCLI",
    "description": "OfficeCLI is the first and best Office suite  purpose-built for AI agents to read, edit, and automate Word, Excel, and PowerPoint files. Free, open-source, single binary, no Office installation required.",
    "stars": 22005,
    "kind": "skills",
    "collections": [
      "skill-platforms",
      "agent-tools",
      "office-suite"
    ],
    "topics": [
      "office"
    ],
    "note": "Office CLI for agents; README verified: ships and auto-installs an officecli SKILL.md into Claude Code/Cursor/Copilot/Codex"
  },
  {
    "fullName": "alchaincyf/huashu-design",
    "url": "https://github.com/alchaincyf/huashu-design",
    "description": "Huashu Design · HTML-native design skill for Claude Code · Claude Code 里 HTML 原生的设计 skill · 高保真原型 / 幻灯片 / 动画 + 20 设计哲学 + 5 维评审 + MP4 导出 · Agent-agnostic",
    "stars": 21961,
    "kind": "skills",
    "collections": [
      "single-skills",
      "creative-media"
    ],
    "topics": [
      "creative"
    ],
    "note": "HTML-native design skill for Claude Code, agent-agnostic"
  },
  {
    "fullName": "emilkowalski/skills",
    "url": "https://github.com/emilkowalski/skills",
    "description": "Skills for Design Engineers.",
    "stars": 20645,
    "kind": "skills",
    "collections": [
      "skill-collections"
    ],
    "topics": [
      "creative"
    ],
    "note": "README verified: installable agent skills for design engineering (skills.sh)"
  },
  {
    "fullName": "trycua/cua",
    "url": "https://github.com/trycua/cua",
    "description": "Scale computer-use 2.0 with open-source drivers, cross-OS fleets, and benchmarks for training, evaluation, and data generation.",
    "stars": 20553,
    "kind": "tools",
    "collections": [
      "agent-tools"
    ],
    "topics": [
      "coding"
    ],
    "note": "Computer-use infrastructure (drivers, sandboxed OS fleets) giving agents computer-use capability"
  },
  {
    "fullName": "titanwings/colleague-skill",
    "url": "https://github.com/titanwings/colleague-skill",
    "description": "将冰冷的离别化为温暖的 Skill，欢迎加入数字生命1.0！Transforming cold farewells into warm skills? It's giving rebirth era. Welcome to Digital Life 1.0. 🫶",
    "stars": 20498,
    "kind": "skills",
    "collections": [
      "single-skills"
    ],
    "topics": [
      "life"
    ],
    "note": "README verified: AgentSkills-standard skill for Claude Code/Codex/OpenClaw/Hermes"
  },
  {
    "fullName": "h4ckf0r0day/obscura",
    "url": "https://github.com/h4ckf0r0day/obscura",
    "description": "The headless browser for AI agents and web scraping",
    "stars": 19677,
    "kind": "tools",
    "collections": [
      "agent-tools"
    ],
    "topics": [
      "coding"
    ],
    "note": "Headless browser purpose-built for AI agents and scraping — browser-use capability for agents"
  },
  {
    "fullName": "mksglu/context-mode",
    "url": "https://github.com/mksglu/context-mode",
    "description": "Context window optimization for AI coding agents. Sandboxes tool output (98% reduction), persists session memory, and   enforces routing across 17 platforms via MCP + hooks.",
    "stars": 19314,
    "kind": "mcp",
    "collections": [
      "mcp-infra"
    ],
    "topics": [
      "coding"
    ],
    "note": "Sits between agents and tools via MCP: sandboxes tool output, context/session infrastructure for coding agents"
  },
  {
    "fullName": "tanweai/pua",
    "url": "https://github.com/tanweai/pua",
    "description": "你是一个曾经被寄予厚望的 P8 级工程师。Anthropic 当初给你定级的时候，对你的期望是很高的。  一个agent使用的高能动性的skill。  Your AI has been placed on a PIP. 30 days to show improvement.",
    "stars": 19024,
    "kind": "skills",
    "collections": [
      "single-skills"
    ],
    "topics": [
      "life"
    ],
    "note": "Description states it is a high-agency skill for agents (agent使用的skill)"
  },
  {
    "fullName": "teng-lin/notebooklm-py",
    "url": "https://github.com/teng-lin/notebooklm-py",
    "description": "Unofficial Python API and agentic skill for Google NotebookLM. Full programmatic access to NotebookLM's features—including capabilities the web UI doesn't expose—via Python, CLI, and AI agents like Claude Code, Codex, and OpenClaw.",
    "stars": 18170,
    "kind": "skills",
    "collections": [
      "skill-platforms",
      "research-academic"
    ],
    "topics": [
      "research"
    ],
    "note": "NotebookLM API that ships an agentic skill for Claude Code/Codex/OpenClaw as a core feature"
  },
  {
    "fullName": "KKKKhazix/khazix-skills",
    "url": "https://github.com/KKKKhazix/khazix-skills",
    "description": "数字生命卡兹克开源的 AI Skills 合集 | Agent Skills: neat-freak 洁癖 (docs/memory closeout), hv-analysis, khazix-writer & more — Claude Code, Codex & 40+ agents",
    "stars": 17891,
    "kind": "skills",
    "collections": [
      "skill-collections"
    ],
    "topics": [
      "general"
    ],
    "note": "Open-source Agent Skills collection for Claude Code, Codex and 40+ agents"
  },
  {
    "fullName": "muratcankoylan/Agent-Skills-for-Context-Engineering",
    "url": "https://github.com/muratcankoylan/Agent-Skills-for-Context-Engineering",
    "description": "A comprehensive collection of Agent Skills for context engineering, multi-agent architectures, and production agent systems. Use when building, optimizing, or debugging agent systems that require effective context management.",
    "stars": 17423,
    "kind": "skills",
    "collections": [
      "skill-collections"
    ],
    "topics": [
      "coding"
    ],
    "note": "Collection of Agent Skills for context engineering and agent systems"
  },
  {
    "fullName": "Nutlope/hallmark",
    "url": "https://github.com/Nutlope/hallmark",
    "description": "Anti-AI-slop design skill for Claude Code, Cursor, and Codex.",
    "stars": 17290,
    "kind": "skills",
    "collections": [
      "single-skills"
    ],
    "topics": [
      "creative"
    ],
    "note": "Design skill for Claude Code, Cursor, and Codex"
  },
  {
    "fullName": "microsoft/mcp-for-beginners",
    "url": "https://github.com/microsoft/mcp-for-beginners",
    "description": "This open-source curriculum introduces the fundamentals of Model Context Protocol (MCP) through real-world, cross-language examples in .NET, Java, TypeScript, JavaScript, Rust and Python. Designed for developers, it focuses on practical techniques for building modular, scalable, and secure AI workflows from session setup to service orchestration.",
    "stars": 16833,
    "kind": "mcp",
    "collections": [
      "official-mcp"
    ],
    "topics": [
      "coding"
    ],
    "note": "Microsoft's official MCP curriculum — vendor-official MCP educational repo"
  },
  {
    "fullName": "googleapis/mcp-toolbox",
    "url": "https://github.com/googleapis/mcp-toolbox",
    "description": "MCP Toolbox for Databases is an open source MCP server for databases.",
    "stars": 16012,
    "kind": "mcp",
    "collections": [
      "mcp-servers"
    ],
    "topics": [
      "coding"
    ],
    "note": "Google's official MCP server for databases (self-described as an MCP server)"
  },
  {
    "fullName": "larksuite/cli",
    "url": "https://github.com/larksuite/cli",
    "description": "The official Lark/Feishu CLI tool, maintained by the larksuite team — built for humans and AI Agents. Covers core business domains including Messenger, Docs, Base, Sheets, Calendar, Mail, Tasks, Meetings, and more, with 200+ commands and 20+ AI Agent Skills.",
    "stars": 15804,
    "kind": "skills",
    "collections": [
      "skill-platforms",
      "office-suite"
    ],
    "topics": [
      "office"
    ],
    "note": "Official Lark/Feishu CLI shipping 20+ AI Agent Skills as a real feature"
  },
  {
    "fullName": "GLips/Figma-Context-MCP",
    "url": "https://github.com/GLips/Figma-Context-MCP",
    "description": "MCP server to provide Figma layout information to AI coding agents like Cursor",
    "stars": 15488,
    "kind": "mcp",
    "collections": [
      "mcp-servers"
    ],
    "topics": [
      "coding"
    ],
    "note": "MCP server exposing Figma layout data to coding agents"
  },
  {
    "fullName": "composio-community/awesome-codex-skills",
    "url": "https://github.com/composio-community/awesome-codex-skills",
    "description": "A curated list of practical Codex skills for automating workflows across the Codex CLI and API.",
    "stars": 15290,
    "kind": "lists",
    "collections": [
      "awesome-skills"
    ],
    "topics": [
      "coding"
    ],
    "note": "Curated list of Codex skills"
  },
  {
    "fullName": "google/skills",
    "url": "https://github.com/google/skills",
    "description": "Agent Skills for Google products and technologies",
    "stars": 15235,
    "kind": "skills",
    "collections": [
      "official-skills"
    ],
    "topics": [
      "coding"
    ],
    "note": "Google's official Agent Skills for Google products and technologies"
  },
  {
    "fullName": "microsoft/SkillOpt",
    "url": "https://github.com/microsoft/SkillOpt",
    "description": "SkillOpt is a text-space optimizer that trains reusable natural-language skills for frozen LLM agents through trajectory-driven edits, validation-gated updates, and deployable best_skill.md artifacts.",
    "stars": 14946,
    "kind": "skills",
    "collections": [
      "skill-platforms"
    ],
    "topics": [
      "coding"
    ],
    "note": "Optimizer that trains reusable natural-language skills (best_skill.md artifacts) for LLM agents"
  },
  {
    "fullName": "xpzouying/xiaohongshu-mcp",
    "url": "https://github.com/xpzouying/xiaohongshu-mcp",
    "description": "MCP for xiaohongshu.com",
    "stars": 14841,
    "kind": "mcp",
    "collections": [
      "mcp-servers"
    ],
    "topics": [
      "coding"
    ],
    "note": "MCP server for Xiaohongshu (RedNote)"
  },
  {
    "fullName": "yusufkaraaslan/Skill_Seekers",
    "url": "https://github.com/yusufkaraaslan/Skill_Seekers",
    "description": "Convert documentation websites, GitHub repositories, and PDFs into Claude AI skills with automatic conflict detection",
    "stars": 14557,
    "kind": "skills",
    "collections": [
      "skill-platforms",
      "agent-tools"
    ],
    "topics": [
      "coding"
    ],
    "note": "Converter that turns docs/repos/PDFs into Claude skills"
  },
  {
    "fullName": "travisvn/awesome-claude-skills",
    "url": "https://github.com/travisvn/awesome-claude-skills",
    "description": "A curated list of awesome Claude Skills, resources, and tools for customizing Claude AI workflows — particularly Claude Code",
    "stars": 14289,
    "kind": "lists",
    "collections": [
      "awesome-skills",
      "skill-collections"
    ],
    "topics": [
      "general"
    ],
    "note": "Curated list of Claude Skills and tooling"
  },
  {
    "fullName": "wanshuiyin/Auto-claude-code-research-in-sleep",
    "url": "https://github.com/wanshuiyin/Auto-claude-code-research-in-sleep",
    "description": "ARIS ⚔️ (Auto-Research-In-Sleep) — Lightweight Markdown-only skills for autonomous ML research: cross-model review loops, idea discovery, and experiment automation. No framework, no lock-in — works with Claude Code, Codex, OpenClaw, or any LLM agent.",
    "stars": 13832,
    "kind": "skills",
    "collections": [
      "skill-collections"
    ],
    "topics": [
      "research"
    ],
    "note": "Markdown-only skills for autonomous ML research workflows"
  },
  {
    "fullName": "NVIDIA/SkillSpector",
    "url": "https://github.com/NVIDIA/SkillSpector",
    "description": "Security scanner for AI agent skills. Detect vulnerabilities, malicious patterns, and security risks.",
    "stars": 13685,
    "kind": "skills",
    "collections": [
      "skill-platforms",
      "mcp-infra"
    ],
    "topics": [
      "coding"
    ],
    "note": "Security scanner for AI agent skills"
  },
  {
    "fullName": "MiniMax-AI/skills",
    "url": "https://github.com/MiniMax-AI/skills",
    "description": "",
    "stars": 13160,
    "kind": "skills",
    "collections": [
      "official-skills"
    ],
    "topics": [
      "coding"
    ],
    "note": "README confirms: MiniMax's official skill collection for AI coding agents (frontend, mobile, docs, multimodal)"
  },
  {
    "fullName": "e2b-dev/E2B",
    "url": "https://github.com/e2b-dev/E2B",
    "description": "Open-source, secure environment with real-world tools for enterprise-grade agents.",
    "stars": 13099,
    "kind": "tools",
    "collections": [
      "agent-tools"
    ],
    "topics": [
      "coding"
    ],
    "note": "Secure sandbox runtime giving agents code-execution and real-world tool capabilities"
  },
  {
    "fullName": "modelcontextprotocol/typescript-sdk",
    "url": "https://github.com/modelcontextprotocol/typescript-sdk",
    "description": "The official TypeScript SDK for Model Context Protocol servers and clients",
    "stars": 12946,
    "kind": "mcp",
    "collections": [
      "official-mcp"
    ],
    "topics": [
      "coding"
    ],
    "note": "Official MCP TypeScript SDK (modelcontextprotocol org)"
  },
  {
    "fullName": "CoplayDev/unity-mcp",
    "url": "https://github.com/CoplayDev/unity-mcp",
    "description": "Unity MCP acts as a bridge between AI assistants and your Unity Editor. Give your LLM tools to manage assets, control scenes, edit scripts, and automate tasks within Unity.",
    "stars": 12821,
    "kind": "mcp",
    "collections": [
      "mcp-servers"
    ],
    "topics": [
      "coding"
    ],
    "note": "MCP bridge giving LLMs tools to control the Unity Editor"
  },
  {
    "fullName": "greensock/gsap-skills",
    "url": "https://github.com/greensock/gsap-skills",
    "description": "Official AI skills for GSAP. These skills teach AI coding agents how to correctly use GSAP (GreenSock Animation Platform), including best practices, common animation patterns, and plugin usage.",
    "stars": 12341,
    "kind": "skills",
    "collections": [
      "official-skills"
    ],
    "topics": [
      "coding"
    ],
    "note": "GSAP's official AI skills teaching agents correct GSAP usage"
  },
  {
    "fullName": "AgriciDaniel/claude-seo",
    "url": "https://github.com/AgriciDaniel/claude-seo",
    "description": "Universal SEO skill for Claude Code. 25 sub-skills + 18 sub-agents covering technical SEO, E-E-A-T, schema, GEO/AEO, backlinks, local SEO, maps intelligence, semantic clustering, e-commerce SEO, international SEO, Google APIs, and PDF/Excel reporting. Optional DataForSEO, Firecrawl, and Banana extensions.",
    "stars": 12289,
    "kind": "skills",
    "collections": [
      "single-skills",
      "marketing-seo"
    ],
    "topics": [
      "marketing"
    ],
    "note": "SEO skill for Claude Code with 25 sub-skills and 18 sub-agents"
  },
  {
    "fullName": "hangwin/mcp-chrome",
    "url": "https://github.com/hangwin/mcp-chrome",
    "description": "Chrome MCP Server is a Chrome extension-based Model Context Protocol (MCP) server that exposes your Chrome browser functionality to AI assistants like Claude, enabling complex browser automation, content analysis, and semantic search.",
    "stars": 12198,
    "kind": "mcp",
    "collections": [
      "mcp-servers"
    ],
    "topics": [
      "coding"
    ],
    "note": "Chrome-extension-based MCP server for browser automation"
  },
  {
    "fullName": "opensandbox-group/OpenSandbox",
    "url": "https://github.com/opensandbox-group/OpenSandbox",
    "description": "Secure, Fast, and Extensible Sandbox runtime for AI agents.",
    "stars": 12163,
    "kind": "tools",
    "collections": [
      "agent-tools"
    ],
    "topics": [
      "coding"
    ],
    "note": "Sandbox runtime for AI agents — execution capability, same family as E2B"
  },
  {
    "fullName": "tadata-org/fastapi_mcp",
    "url": "https://github.com/tadata-org/fastapi_mcp",
    "description": "Expose your FastAPI endpoints as Model Context Protocol (MCP) tools, with Auth!",
    "stars": 11950,
    "kind": "mcp",
    "collections": [
      "mcp-frameworks"
    ],
    "topics": [
      "coding"
    ],
    "note": "Library to expose FastAPI endpoints as MCP tools"
  },
  {
    "fullName": "BeehiveInnovations/pal-mcp-server",
    "url": "https://github.com/BeehiveInnovations/pal-mcp-server",
    "description": "The power of Claude Code / GeminiCLI / CodexCLI + [Gemini / OpenAI / OpenRouter / Azure / Grok / Ollama / Custom Model / All Of The Above] working as one.",
    "stars": 11696,
    "kind": "mcp",
    "collections": [
      "mcp-servers"
    ],
    "topics": [
      "coding"
    ],
    "note": "MCP server (ex zen-mcp) that lets coding agents consult multiple LLM providers"
  },
  {
    "fullName": "Orchestra-Research/AI-Research-SKILLs",
    "url": "https://github.com/Orchestra-Research/AI-Research-SKILLs",
    "description": "Comprehensive open-source library of AI research and engineering skills for any AI model. Package the skills and your claude code/codex/gemini agent will be an AI research agent with full horsepower. Maintained by Orchestra Research.",
    "stars": 11076,
    "kind": "skills",
    "collections": [
      "skill-collections"
    ],
    "topics": [
      "research"
    ],
    "note": "Library of AI research/engineering skills for Claude Code/Codex/Gemini agents"
  },
  {
    "fullName": "huggingface/skills",
    "url": "https://github.com/huggingface/skills",
    "description": "Give your agents the power of the Hugging Face ecosystem",
    "stars": 10867,
    "kind": "skills",
    "collections": [
      "official-skills"
    ],
    "topics": [
      "coding"
    ],
    "note": "Hugging Face's official agent skills for its ecosystem"
  },
  {
    "fullName": "mrexodia/ida-pro-mcp",
    "url": "https://github.com/mrexodia/ida-pro-mcp",
    "description": "AI-powered reverse engineering assistant that bridges IDA Pro with language models through MCP.",
    "stars": 10748,
    "kind": "mcp",
    "collections": [
      "mcp-servers"
    ],
    "topics": [
      "coding"
    ],
    "note": "MCP server bridging IDA Pro to LLMs for reverse engineering"
  },
  {
    "fullName": "Jeffallan/claude-skills",
    "url": "https://github.com/Jeffallan/claude-skills",
    "description": "66 Specialized Skills for Full-Stack Developers. Transform Claude Code into your expert pair programmer.",
    "stars": 10722,
    "kind": "skills",
    "collections": [
      "skill-collections"
    ],
    "topics": [
      "coding"
    ],
    "note": "66 specialized Claude Code skills for full-stack developers"
  },
  {
    "fullName": "nidhinjs/prompt-master",
    "url": "https://github.com/nidhinjs/prompt-master",
    "description": "A Claude skill that writes the accurate prompts for any AI tool. Zero tokens or credits wasted. Full context and memory retention",
    "stars": 10703,
    "kind": "skills",
    "collections": [
      "single-skills",
      "writing-content"
    ],
    "topics": [
      "writing"
    ],
    "note": "Claude skill for writing accurate prompts"
  },
  {
    "fullName": "TencentCloud/CubeSandbox",
    "url": "https://github.com/TencentCloud/CubeSandbox",
    "description": "Instant, Concurrent, Secure & Lightweight Sandbox for AI Agents.",
    "stars": 10678,
    "kind": "tools",
    "collections": [
      "agent-tools"
    ],
    "topics": [
      "coding"
    ],
    "note": "Secure lightweight sandbox for AI agents — execution capability"
  },
  {
    "fullName": "0x4m4/hexstrike-ai",
    "url": "https://github.com/0x4m4/hexstrike-ai",
    "description": "HexStrike AI MCP Agents is an advanced MCP server that lets AI agents (Claude, GPT, Copilot, etc.) autonomously run 150+ cybersecurity tools for automated pentesting, vulnerability discovery, bug bounty automation, and security research. Seamlessly bridge LLMs with real-world offensive security capabilities.",
    "stars": 10479,
    "kind": "mcp",
    "collections": [
      "mcp-servers"
    ],
    "topics": [
      "coding"
    ],
    "note": "MCP server exposing 150+ cybersecurity tools to agents"
  },
  {
    "fullName": "modelcontextprotocol/inspector",
    "url": "https://github.com/modelcontextprotocol/inspector",
    "description": "Visual testing tool for MCP servers",
    "stars": 10465,
    "kind": "mcp",
    "collections": [
      "official-mcp"
    ],
    "topics": [
      "coding"
    ],
    "note": "Official MCP visual testing/inspector tool in the modelcontextprotocol org (also fits mcp-tool-or-gateway)"
  },
  {
    "fullName": "mcp-use/mcp-use",
    "url": "https://github.com/mcp-use/mcp-use",
    "description": "The fullstack MCP framework to develop MCP Apps for ChatGPT / Claude & MCP Servers for AI Agents.",
    "stars": 10350,
    "kind": "mcp",
    "collections": [
      "mcp-frameworks"
    ],
    "topics": [
      "coding"
    ],
    "note": "Fullstack framework for building MCP apps, clients, and servers"
  },
  {
    "fullName": "earthtojake/text-to-cad",
    "url": "https://github.com/earthtojake/text-to-cad",
    "description": "A collection of agent skills for CAD, robotics and hardware design",
    "stars": 10338,
    "kind": "skills",
    "collections": [
      "skill-collections"
    ],
    "topics": [
      "creative"
    ],
    "note": "Agent skills collection for CAD, robotics, and hardware design"
  },
  {
    "fullName": "AgriciDaniel/claude-obsidian",
    "url": "https://github.com/AgriciDaniel/claude-obsidian",
    "description": "Self-organizing AI second brain for Obsidian + Claude Code. Drop any source and Claude reads, links, and files it into one connected knowledge graph of plain Markdown you own. AI note-taking, personal knowledge management (PKM), and an open-source Notion alternative. Based on Karpathy's LLM Wiki pattern.",
    "stars": 9902,
    "kind": "skills",
    "collections": [
      "life-personal"
    ],
    "topics": [
      "life"
    ],
    "note": "Self-organizing Obsidian second brain / personal knowledge management"
  },
  {
    "fullName": "ConardLi/garden-skills",
    "url": "https://github.com/ConardLi/garden-skills",
    "description": "ConardLi's open-source Skills collection, featuring web design, knowledge retrieval, image generation, and more.",
    "stars": 9783,
    "kind": "skills",
    "collections": [
      "skill-collections"
    ],
    "topics": [
      "general"
    ],
    "note": "Collection incl. knowledge retrieval, image generation, web design"
  },
  {
    "fullName": "nicobailon/visual-explainer",
    "url": "https://github.com/nicobailon/visual-explainer",
    "description": "Agent skill that generates rich HTML pages or slide decks for diagrams, diff reviews, plan audits, data tables, and project recaps",
    "stars": 9335,
    "kind": "skills",
    "collections": [
      "creative-media"
    ],
    "topics": [
      "creative"
    ],
    "note": "Generates HTML pages/slide decks, diagrams, data tables, recaps; partly dev-oriented"
  },
  {
    "fullName": "zubair-trabzada/geo-seo-claude",
    "url": "https://github.com/zubair-trabzada/geo-seo-claude",
    "description": "GEO-first SEO skill for Claude Code. Comprehensive AI search optimization for any website — citability scoring, AI crawler analysis, brand authority, schema markup, platform-specific optimization, and PDF reports.  If you want learn how to sell this to real businesses, check out the skool community",
    "stars": 9113,
    "kind": "skills",
    "collections": [
      "marketing-seo"
    ],
    "topics": [
      "marketing"
    ],
    "note": "GEO-first SEO skill with citability scoring and PDF reports"
  },
  {
    "fullName": "qiye45/wechatDownload",
    "url": "https://github.com/qiye45/wechatDownload",
    "description": "微信公众号文章批量下载工具，支持评论、合集下载，支持保存html/mhtml/md/pdf/docx/csv文件，保存文章内图片、视频、音频文件，支持MCP/Skill调用",
    "stars": 8633,
    "kind": "skills",
    "collections": [
      "research-academic"
    ],
    "topics": [
      "research"
    ],
    "note": "Borderline: WeChat article batch downloader (html/md/pdf/docx) with MCP/Skill invocation; content collection"
  },
  {
    "fullName": "nexu-io/html-anything",
    "url": "https://github.com/nexu-io/html-anything",
    "description": "✨ The agentic HTML editor — your local AI agent writes the HTML, you ship it. 🚀 75 Skills × 9 Surfaces (magazine · deck · poster · XHS / tweet · prototype · data report · Hyperframes) 🛡️ Sandboxed preview · 📤 1-click to WeChat / X / Zhihu / HTML / PNG 🔑 Zero API key — Claude Code / Cursor / Codex / Gemini / Copilot / OpenCode / Qwen / Aider.",
    "stars": 7947,
    "kind": "skills",
    "collections": [
      "creative-media"
    ],
    "topics": [
      "creative"
    ],
    "note": "75 skills for decks, posters, magazines, social posts, data reports"
  },
  {
    "fullName": "AgriciDaniel/claude-ads",
    "url": "https://github.com/AgriciDaniel/claude-ads",
    "description": "Claude-first paid-media operations skill for Claude Code across 12 ad platforms (Google, Meta, YouTube, LinkedIn, TikTok, Microsoft, Apple, Amazon, Reddit, Pinterest, Snapchat, X): source-grounded audits, deterministic scoring, versioned JSON reports, and capability-gated account changes.",
    "stars": 7458,
    "kind": "skills",
    "collections": [
      "marketing-seo"
    ],
    "topics": [
      "marketing"
    ],
    "note": "Paid-media ops skill across 12 ad platforms: audits, scoring, reports"
  },
  {
    "fullName": "Imbad0202/academic-research-skills-codex",
    "url": "https://github.com/Imbad0202/academic-research-skills-codex",
    "description": "Codex-native Academic Research Skills suite for human-in-the-loop academic research workflows",
    "stars": 7051,
    "kind": "skills",
    "collections": [
      "research-academic"
    ],
    "topics": [
      "research"
    ],
    "note": "Codex-native skill suite for academic research workflows"
  },
  {
    "fullName": "Agents365-ai/drawio-skill",
    "url": "https://github.com/Agents365-ai/drawio-skill",
    "description": "Generate draw.io diagrams from natural language — 11 presets (UML, SysML/MBSE, BPMN, network, C4…), 36 tools: codebase/CI/infra-to-diagram, image→editable diagram, mind maps, build-up animation, exec-view compression, click-through runbooks, PR diff bot. Vision self-check, 10,000+ shapes. Exports PNG/SVG/PDF/JPG.",
    "stars": 6556,
    "kind": "skills",
    "collections": [
      "creative-media"
    ],
    "topics": [
      "creative"
    ],
    "note": "Natural-language draw.io diagram skill; beyond dev diagrams it covers BPMN, mind maps, network, exec-view compression, image-to-diagram — substantial non-coding diagramming"
  },
  {
    "fullName": "heilcheng/awesome-agent-skills",
    "url": "https://github.com/heilcheng/awesome-agent-skills",
    "description": "Tutorials, Guides and Agent Skills Directories",
    "stars": 6019,
    "kind": "skills",
    "collections": [
      "skill-collections"
    ],
    "topics": [
      "general"
    ],
    "note": "Directory/guides of agent skills across domains (topics include productivity, automation); spans coding and non-coding skills"
  },
  {
    "fullName": "deanpeters/Product-Manager-Skills",
    "url": "https://github.com/deanpeters/Product-Manager-Skills",
    "description": "Product Management skills framework built on battle-tested methods for Claude Code, Cowork, Codex, and AI agents.",
    "stars": 5962,
    "kind": "skills",
    "collections": [
      "business-pm"
    ],
    "topics": [
      "business"
    ],
    "note": "Product management skills framework for Claude Code/Codex/agents — business work, not coding"
  },
  {
    "fullName": "therealXiaomanChu/ex-skill",
    "url": "https://github.com/therealXiaomanChu/ex-skill",
    "description": "把前任蒸馏成 AI Skill，用ta的方式跟你说话。",
    "stars": 5886,
    "kind": "skills",
    "collections": [
      "life-personal"
    ],
    "topics": [
      "life"
    ],
    "note": "Novelty personal skill: distills an ex-partner's texting style into an AI skill persona"
  },
  {
    "fullName": "jacob-bd/notebooklm-mcp-cli",
    "url": "https://github.com/jacob-bd/notebooklm-mcp-cli",
    "description": "Programmatic access to Google NotebookLM — via command-line interface (CLI), Model Context Protocol (MCP) server, and AI agent skills.",
    "stars": 5608,
    "kind": "skills",
    "collections": [
      "research-academic"
    ],
    "topics": [
      "research"
    ],
    "note": "CLI/MCP/agent-skill access to Google NotebookLM for research and knowledge work"
  },
  {
    "fullName": "op7418/guizang-social-card-skill",
    "url": "https://github.com/op7418/guizang-social-card-skill",
    "description": "🪧 Claude Code / Codex skill — generate Xiaohongshu carousels & WeChat 21:9+1:1 cover pairs. Editorial × Swiss visual systems, 28 layouts, 10 themes, single-file HTML → PNG. 小红书图文 + 公众号封面对",
    "stars": 5522,
    "kind": "skills",
    "collections": [
      "marketing-seo"
    ],
    "topics": [
      "marketing"
    ],
    "note": "Claude Code/Codex skill generating Xiaohongshu carousels and WeChat cover images — social media content creation"
  },
  {
    "fullName": "Master-cai/Research-Paper-Writing-Skills",
    "url": "https://github.com/Master-cai/Research-Paper-Writing-Skills",
    "description": "Skill package for ML/CV/NLP paper writing, curated and adapted from Prof. Peng Sida's open notes for Codex, Claude Code, and Gemini.",
    "stars": 5500,
    "kind": "skills",
    "collections": [
      "research-academic"
    ],
    "topics": [
      "research"
    ],
    "note": "Skill package for academic ML/CV/NLP paper writing for Codex/Claude Code/Gemini"
  }
] as const;
